<header>
        
        <nav class="navbar navbar-dark bg-dark nav-border ">
        <a class="navbar-brand" href="login.php">CabsOnline</a>

        <ul class="nav">

            <li class="nav-item">
                <a class="nav-link active" href="login.php">Login</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="register.php">Register</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="booking.php">Book Cab</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="admin.php">Admin</a>
            </li>
            

        
        
        </ul>

        </nav>

    </header>
    <div class="wrap">